In [2]:
import numpy.random as npr

In [2]:
from random import shuffle

In [4]:
a = [[1,2], [3,4]]
b = [5,6]
xy = zip(a,b)
shuffle(xy)
a, b = zip(*xy)
print a, b

([3, 4], [1, 2]) (6, 5)


In [ ]:
def make_sampling_table():
    

In [7]:
import numpy as np

In [17]:
rands = npr.uniform(size=[2,3])
sums = np.ones([2,3])*.5
idxs = np.zeros([2,3])
print rands
print sums

[[ 0.79033443  0.50080002  0.48984771]
 [ 0.28998082  0.26119588  0.02096962]]
[[ 0.5  0.5  0.5]
 [ 0.5  0.5  0.5]]


In [21]:
new = sums <= rands
print new
print np.all(new)
idxs[new] = 10

[[ True  True False]
 [False False False]]
False


In [22]:
print idxs

[[ 10.  10.   0.]
 [  0.   0.   0.]]
